# Generated by Django 3.0 on 2022-12-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lettings", "0002_auto_20221208_1626"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO lettings_letting (
                id,
                title,
                address_id
            )
            SELECT
                id,
                title,
                address_id
            FROM
                oc_lettings_site_letting;
        """,
            reverse_sql="""
            INSERT INTO lettings_letting (
                id,
                title,
                address_id
            )
            SELECT
                id,
                title,
                address_id
            FROM
                oc_lettings_site_letting;
        """,
        ),
    ]
