version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.11.1
        environment:
          SECRET_KEY:$SECRET_KEY
          SENTRY_KEY:$SENTRY_KEY
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Install environement
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: execute linter
          command: |
            . venv/bin/activate
            flake8
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pytest
      - store_artifacts:
          path: test-reports/
          destination: python_app
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Deploy to Dockerhub
          command: |
            docker build -t oc-lettings-mb .
            docker login --username $DOCKERHUB_LOGIN --password $DOCKERHUB_PASSWORD
            docker tag oc-lettings-mb $DOCKERHUB_LOGIN/oc-lettings-mb:$CIRCLE_SHA1
            docker tag oc-lettings-mb $DOCKERHUB_LOGIN/oc-lettings-mb:latest
            docker push $DOCKERHUB_LOGIN/oc-lettings-mb --all-tags
      - run:
          name: Deploy to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            heroku container:login
            heroku container:push -a oc-lettings-mb web
            heroku container:release -a oc-lettings-mb web
workflows:
  my_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main