# Generated by Django 3.0 on 2022-12-15 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oc_lettings_site", "0001_initial"),
        ("lettings", "0002_auto_20221208_1626"),
        ("profiles", "0002_auto_20221208_1704"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="Letting",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
