# Generated by Django 3.0 on 2022-12-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oc_lettings_site", "0002_auto_20221208_1655"),
        ("profiles", "0002_auto_20221208_1704"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
